language: ruby
sudo: false
dist: trusty
cache: bundler
rvm:
  - 2.2.5
  - 2.3.1
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
jdk:
  - oraclejdk8
before_install:
  - gem install bundler
  - gem update bundler
